### PR TITLE
Specify SSL certificate under config_schema

### PR DESCRIPTION
**Pull request by UtkarshVerma**
It would be much more intuitive to let this lib also specify the SSL certificate.

### CODE REVIEW

**Comment by rojer** [comment]
syntax is invalid (missing closing quote). have you actually verified that it works?

**Comment by UtkarshVerma** [comment]
@rojer It should work. All I did was transfer the `mqtt.ssl_ca_cert` key from the app's mos.yml file to the lib's.

**Comment by rojer** [comment]
well, should is not the same as does.

but more importantly, because non-empty ssl_ca_cert turns on ssl, this change would break non-ssl connections for existing users.
so, unfortunately, in this form this is a no go.

**Comment by tripflex** [comment]
@UtkarshVerma you can always just fork the repo and use your own in your `mos.yml` file .. that's what I did for the ca-bundle since I didn't need all the certs for AWS/Azure, and it reduced amount of space used on device (since we all know it's very limited)

Then you just use your github URL in the `mos.yml` and voila

**Pull request closed without merging**
